Repository 42-Gang/user-server, pull requests merged in 2025-04, with the labels that each got.

#3 [FEAT]1 rest api 구현
  package.json
  prisma/schema.prisma
  src/app.ts
  src/plugins/container.ts
  src/plugins/router.ts
  src/plugins/swagger/swagger-plugin.ts
  src/v1/apis/auth/auth.controller.ts
  src/v1/apis/auth/auth.route.ts
  src/v1/apis/auth/auth.schema.ts
  src/v1/apis/auth/auth.service.ts
  src/v1/apis/schemas/authenticateUser.schema.ts
  src/v1/apis/schemas/createUser.schema.ts
  src/v1/apis/schemas/editNickname.schema.ts
  src/v1/apis/schemas/getUser.schema.ts
  src/v1/apis/schemas/searchUser.schema.ts
  src/v1/apis/schemas/users.schema.ts
  src/v1/apis/users.controller.ts
  src/v1/apis/users.route.ts
  src/v1/apis/users.service.ts
  src/v1/apis/users/user.schema.ts
  src/v1/apis/users/users.controller.ts
  src/v1/apis/users/users.route.ts
  src/v1/apis/users/users.schema.ts
  src/v1/apis/users/users.service.ts
  src/v1/common/types/fastify.d.ts
  src/v1/index.ts
  src/v1/storage/database/interfaces/user.repository.interface.ts
  src/v1/storage/database/prisma/user.repository.ts
Labels: ⚙ Setting, ✨ Feature, 📬 API

#4 [FEAT] 2 온라인 상태 확인 기능 구현
  @types/global.d.ts
  package.json
  prisma/schema.prisma
  src/app.ts
  src/plugins/container.ts
  src/plugins/http.client.ts
  src/plugins/http/got/http.client.ts
  src/plugins/http/interface/http.client.interface.ts
  src/plugins/kafka.ts
  src/plugins/redis.ts
  src/plugins/socket.ts
  src/server-config.ts
  src/v1/apis/schemas/users.schema.ts
  src/v1/apis/users.service.ts
  src/v1/common/types/socket.d.ts
  src/v1/index.ts
  src/v1/sockets/chat/chat.namespace.ts
  src/v1/sockets/chat/chat.schema.ts
  src/v1/sockets/gateway.ts
  src/v1/sockets/status/connection.handler.ts
  src/v1/sockets/status/friends.schema.ts
  src/v1/sockets/status/kafka/constants.ts
  src/v1/sockets/status/kafka/consumer.handlers.ts
  src/v1/sockets/status/kafka/consumer.ts
  src/v1/sockets/status/kafka/messages.schema.ts
  src/v1/sockets/status/kafka/producer.ts
  src/v1/sockets/status/status.namespace.ts
  src/v1/sockets/status/status.schema.ts
  src/v1/sockets/status/status.service.ts
  src/v1/sockets/utils/auth.ts
  src/v1/sockets/utils/errorHandler.ts
  src/v1/sockets/utils/middleware.ts
  src/v1/sockets/utils/token.ts
  src/v1/storage/cache/interfaces/friend.cache.interface.ts
  src/v1/storage/cache/redis/friend.cache.repository.ts
  test/plugins/http/got/http.client.spec.ts
  test/v1/apis/auth/services/auth.service.spec.ts
  test/v1/sockets/send-friend-event.js
  wiremock/docker-compose.yaml
  wiremock/mappings/get-friends-1.json
  wiremock/mappings/get-friends-2.json
  wiremock/mappings/token-verify.json
Labels: ✨ Feature

#7 5 refactor 친구 서버 유저 서버 통합 v2
  prisma/schema.prisma
  src/v1/apis/friends/friends.controller.ts
  src/v1/apis/friends/friends.route.ts
  src/v1/apis/friends/friends.schema.ts
  src/v1/apis/friends/friends.service.ts
  src/v1/apis/users/schemas/authenticateUser.schema.ts
  src/v1/apis/users/schemas/createUser.schema.ts
  src/v1/apis/users/schemas/editNickname.schema.ts
  src/v1/apis/users/schemas/getUser.schema.ts
  src/v1/apis/users/schemas/searchUser.schema.ts
  src/v1/apis/users/schemas/users.schema.ts
  src/v1/apis/users/users.controller.ts
  src/v1/apis/users/users.route.ts
  src/v1/apis/users/users.service.ts
  src/v1/index.ts
  src/v1/sockets/status/status.namespace.ts
  src/v1/storage/database/interfaces/friend.repository.interface.ts
  src/v1/storage/database/prisma/friend.repository.ts
Labels: 🔨 Refactor

#13 [FEAT] 12 친구 관련 api 테스트코드 작성
  src/v1/apis/friends/friends.service.ts
  src/v1/storage/database/interfaces/friend.repository.interface.ts
  test/plugins/http/got/http.client.spec.ts
  test/v1/apis/friends/services/friends.services.spec.ts
Labels: ✅ Test

#14 [TEST] 10 유저서버 테스트코드 작성 유저관련 api
  test/v1/apis/friends/friends.service.spec.ts
  test/v1/apis/users/users.service.spec.ts
Labels: ✅ Test

#16 [REFACTOR] 15 사용자 실시간 상태 기능 수정
  src/app.ts
  src/plugins/http.client.ts
  src/plugins/router.ts
  src/plugins/socket.ts
  src/v1/common/types/socket.d.ts
  src/v1/sockets/status/connection.handler.ts
  src/v1/sockets/status/friends.schema.ts
  src/v1/sockets/status/status.namespace.ts
  src/v1/sockets/status/status.service.ts
  src/v1/sockets/utils/auth.ts
  src/v1/sockets/utils/middleware.ts
  src/v1/sockets/utils/token.ts
  src/v1/storage/database/interfaces/friend.repository.interface.ts
  src/v1/storage/database/prisma/friend.repository.ts
Labels: 🔨 Refactor

#18 [FEAT] 17 internal api에 대한 보안 로직 추가 이메일 중복 확인 api 개발
  src/app.ts
  src/plugins/router.ts
  src/v1/apis/users/schemas/authenticate-user.schema.ts
  src/v1/apis/users/schemas/check-duplicated-email.schema.ts
  src/v1/apis/users/schemas/create-user.schema.ts
  src/v1/apis/users/schemas/edit-nickname.schema.ts
  src/v1/apis/users/schemas/get-user.schema.ts
  src/v1/apis/users/schemas/search-user.schema.ts
  src/v1/apis/users/users.controller.ts
  src/v1/apis/users/users.route.ts
  src/v1/apis/users/users.service.ts
  src/v1/common/schema/core.schema.ts
  src/v1/common/types/fastify.d.ts
  test/v1/apis/friends/friends.service.spec.ts
Labels: ⚙ Setting, ✨ Feature

#21 [FEAT] 8 친구 기능 API
  src/v1/apis/friends/friends.controller.ts
  src/v1/apis/friends/friends.route.ts
  src/v1/apis/friends/friends.schema.ts
  src/v1/apis/friends/friends.service.ts
  src/v1/apis/friends/schemas/get-friends.schema.ts
  src/v1/apis/friends/schemas/get-requests.schema.ts
  src/v1/apis/friends/schemas/get-status.schema.ts
  test/v1/apis/friends/friends.service.spec.ts
Labels: ✅ Test, ✨ Feature, 📬 API

#20 [FEAT] 19 친구 기능 kafka 관련 설정 추가
  .gitignore
  src/v1/apis/friends/friends.service.ts
  src/v1/apis/friends/schemas/get-friends.schema.ts
  src/v1/apis/friends/schemas/get-requests.schema.ts
  src/v1/kafka/friends/producer.ts
  src/v1/sockets/status/kafka/constants.ts
  src/v1/sockets/status/kafka/consumer.handlers.ts
  src/v1/sockets/status/kafka/consumer.ts
  src/v1/sockets/status/kafka/friend.consumer.ts
  src/v1/sockets/status/kafka/messages.schema.ts
  src/v1/sockets/status/kafka/user-status.consumer.ts
  test/v1/apis/friends/friends.service.spec.ts
Labels: ✨ Feature

#30 [REFACTOR] 28 친구 관련 api 버그 및 리펙토링
  src/server-config.ts
  src/v1/apis/friends/friends.service.ts
  src/v1/apis/friends/schemas/get-status.schema.ts
  src/v1/apis/users/schemas/search-user.schema.ts
  src/v1/apis/users/users.service.ts
Labels: 🔨 Refactor

#33 [REFACTOR] 소켓 상태 Kafka Consumer 코드 정리
  src/v1/sockets/status/kafka/consumer.ts
  src/v1/sockets/status/kafka/friend.consumer.ts
  src/v1/sockets/status/status.namespace.ts
Labels: 🔨 Refactor

#34 [REFACTOR] 사용자 닉네임 중복 검사 기능 추가
  src/v1/apis/users/users.service.ts
  src/v1/storage/database/interfaces/user.repository.interface.ts
  src/v1/storage/database/prisma/user.repository.ts
  test/v1/apis/users/users.service.spec.ts
Labels: 🔨 Refactor

#35 [REFACTOR] 26 유저db 친구db schema 통합
  prisma/schema.prisma
  src/v1/apis/friends/friends.controller.ts
  src/v1/apis/friends/friends.service.ts
  src/v1/apis/friends/schemas/friend.schema.ts
  src/v1/apis/friends/schemas/get-friends.schema.ts
  src/v1/apis/friends/schemas/get-requests.schema.ts
  src/v1/storage/database/interfaces/friend.repository.interface.ts
  src/v1/storage/database/prisma/friend.repository.ts
  test/v1/apis/friends/friends.service.spec.ts
Labels: 🔨 Refactor

#39 [REFACTOR] 38 kafka consumer 구조 변경
  src/main.ts
  src/plugins/socket.ts
  src/v1/kafka/constants.ts
  src/v1/kafka/consumer.ts
  src/v1/kafka/consumers/friend.topic.handler.ts
  src/v1/kafka/consumers/kafka.topic.handler.ts
  src/v1/kafka/consumers/user-status.topic.handler.ts
  src/v1/kafka/producer.ts
  src/v1/kafka/schemas/messages.schema.ts
  src/v1/sockets/gateway.ts
  src/v1/sockets/status/connection.handler.ts
  src/v1/sockets/status/kafka/consumer.ts
  src/v1/sockets/status/kafka/friend.consumer.ts
  src/v1/sockets/status/kafka/user-status.consumer.ts
  src/v1/sockets/status/startStatusNamespace.ts
  src/v1/sockets/utils/auth.ts
Labels: ⚙ Setting, ✨ Feature, 🔨 Refactor

#41 [REFACTOR] 버그 및 리펙토링 (중요X)
  src/main.ts
  src/server-config.ts
  src/v1/apis/friends/friends.service.ts
  src/v1/apis/friends/schemas/get-requests.schema.ts
  src/v1/sockets/utils/auth.ts
Labels: 🔨 Refactor

#40 [REFACTOR] 26 유저검색 api 수정
  src/v1/apis/friends/friends.route.ts
  src/v1/apis/users/schemas/search-user.schema.ts
  src/v1/apis/users/users.controller.ts
  src/v1/apis/users/users.route.ts
  src/v1/apis/users/users.service.ts
  src/v1/kafka/consumers/user-status.topic.handler.ts
  src/v1/storage/database/interfaces/user.repository.interface.ts
  src/v1/storage/database/prisma/user.repository.ts
  test/v1/apis/users/users.service.spec.ts
Labels: 🔨 Refactor

#42 Feature/친구관련 kafka 기능 추가
  src/v1/apis/friends/friends.service.ts
  src/v1/kafka/constants.ts
  src/v1/kafka/consumer.ts
  src/v1/kafka/producers/friend.producer.ts
  src/v1/kafka/producers/user-status.producer.ts
  src/v1/sockets/status/connection.handler.ts
Labels: ✨ Feature

#43 [REFACTOR] 사용자 상태 확인 기능 버그 수정
  src/v1/kafka/consumers/friend.topic.handler.ts
  src/v1/sockets/status/status.service.ts
  src/v1/storage/database/interfaces/friend.repository.interface.ts
  src/v1/storage/database/prisma/friend.repository.ts
Labels: 🔨 Refactor
