Repository 42-Gang/user-server, pull requests merged in 2025-05, with the labels that each got.

#44 Feature/36 친구 요청 알림 친구 수락 알림
  src/v1/kafka/consumers/friend.topic.handler.ts
  src/v1/kafka/schemas/messages.schema.ts
  src/v1/sockets/friend/connection.handler.ts
  src/v1/sockets/friend/startFriendNamespace.ts
  src/v1/sockets/gateway.ts
  src/v1/sockets/status/connection.handler.ts
  src/v1/sockets/utils/middleware.ts
  wiremock/mappings/token-verify.json
Labels: ✨ Feature

#45 [REFACTOR] 컨슈머 시작 위치 변경 (fromBeginning = false)
  src/v1/kafka/consumers/friend.topic.handler.ts
  src/v1/kafka/consumers/user-status.topic.handler.ts
Labels: 🔨 Refactor

#46 fix: 에러 메시지 국문으로 수정
  src/app.ts
  src/v1/apis/friends/friends.service.ts
  src/v1/apis/users/users.service.ts
  test/v1/apis/friends/friends.service.spec.ts
  test/v1/apis/users/users.service.spec.ts
Labels: 🐞 BugFix

#49 [FEATURE] 로그아웃 이벤트 consumer 핸들러 추가
  src/v1/kafka/constants.ts
  src/v1/kafka/consumer.ts
  src/v1/kafka/consumers/auth.topic.handler.ts
  src/v1/kafka/consumers/friend.topic.handler.ts
  src/v1/kafka/schemas/messages.schema.ts
  src/v1/sockets/friend/connection.handler.ts
  src/v1/sockets/friend/startFriendNamespace.ts
Labels: ✨ Feature

#50 [FEATURE] 아바타 이미지 consumer
  src/v1/kafka/constants.ts
  src/v1/kafka/consumer.ts
  src/v1/kafka/consumers/image.topic.handler.ts
  src/v1/kafka/schemas/image-topic.schema.ts
Labels: ✨ Feature

#51 [FEATURE] kafka consumer 유저 상태 확인
  src/v1/kafka/consumers/friend.topic.handler.ts
  src/v1/kafka/consumers/user-status.topic.handler.ts
  src/v1/kafka/schemas/messages.schema.ts
Labels: ✨ Feature

#54 [FIX] 53 친구 요청 관련 카프카 수정
  src/v1/kafka/consumers/friend.topic.handler.ts
  src/v1/kafka/consumers/user-status.topic.handler.ts
  src/v1/kafka/producers/user-status.producer.ts
Labels: 🐞 BugFix

#56 [FIX] friend topic nickname 수정
  src/v1/kafka/consumers/friend.topic.handler.ts
Labels: 🐞 BugFix

#62 [FIX] 닉네임 변경 시 중복 에러 처리 수정
  src/v1/apis/users/users.route.ts
  src/v1/apis/users/users.service.ts
  src/v1/kafka/consumers/friend.topic.handler.ts
  test/v1/apis/users/users.service.spec.ts
Labels: 🐞 BugFix

#63 [FEATURE] 아바타 삭제 기능 추가
  src/v1/apis/users/schemas/delete-avatar.schema.ts
  src/v1/apis/users/users.controller.ts
  src/v1/apis/users/users.route.ts
  src/v1/apis/users/users.service.ts
  test/v1/apis/users/users.service.spec.ts
Labels: ✨ Feature, 📬 API

#65 [FIX] 검색 결과 에러
  Dockerfile
  src/v1/apis/users/users.route.ts
Labels: 🐞 BugFix

#68 [FEAT] 유저 검색 시 반환되는 필드 수정
  src/v1/apis/users/schemas/search-user.schema.ts
  wiremock/mappings/file-server.json
Labels: 🔨 Refactor

#70 [FIX] 친구 추가 시 상대방의 상태 업데이트 제거
  src/v1/kafka/consumers/friend.topic.handler.ts
Labels: 🐞 BugFix

#72 [FIX] friends 테스트코드 수정
  src/plugins/http.client.ts
  src/v1/apis/file/file.service.ts
  src/v1/sockets/utils/auth.ts
  test/v1/apis/friends/friends.service.spec.ts
  test/v1/mocks/mockHttpClient.ts
Labels: ✅ Test, 🐞 BugFix

#75 [FIX] 버그 수정
  .dockerignore
  Dockerfile
  prisma/migrations/20250527134109_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  src/v1/apis/friends/friends.service.ts
  src/v1/apis/friends/schemas/get-requests.schema.ts
  src/v1/kafka/consumer.ts
  src/v1/kafka/consumers/friend.topic.handler.ts
  src/v1/kafka/consumers/user-status.topic.handler.ts
  src/v1/sockets/status/connection.handler.ts
  src/v1/sockets/status/friends.schema.ts
  src/v1/sockets/status/status.service.ts
  src/v1/storage/database/prisma/friend.repository.ts
  test/v1/apis/friends/friends.service.spec.ts
  test/v1/apis/users/users.service.spec.ts
  wiremock/mappings/token-verify.json
Labels: ⚙ Setting, 🐞 BugFix
